language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install .

script: 
  - flake8 *.py tests --exclude=ez_setup.py --max-line-length=100
  - nosetests --with-coverage --cover-package nested_dict
              --cover-inclusive --cover-min-percentage 85
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then make -C docs html; fi
  - if [[ $TRAVIS_PYTHON_VERSION > 3.2 ]]; then make -C docs html; fi
